name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build the API Docker image
      run: docker build ./flipping-calculator-api --file ./flipping-calculator-api/Dockerfile --tag flipping-calculator-api:$(date +%s)
    - name: Build the Frontend Docker image
      run: docker build ./flipping-calculator-frontend --file ./flipping-calculator-frontend/Dockerfile --tag flipping-calculator-frontend:$(date +%s)
